#-------------------------------
# General Site Settings

title: BareWare Games
description: Simply natural.
email: barewaregames@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Projects, url: '#projects'}
- {name: Staff, url: '#staff'}
- {name: Contact, url: '#contact'}
- {name: Donate, url: '#donate'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/b/116392188754803429731/116392188754803429731/about?hl=en&service=PLUS'
  rel-publisher: 'https://plus.google.com/b/116392188754803429731/116392188754803429731/about?hl=en&service=PLUS'

#-------------------------------
# Header Section

header:
- {avatar: 'building-bg.jpg'}
- {avatar: 'game-bg 2.jpg'}

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Bareware Games creates the most natural** form of gaming. Undertaking projects,
  creating a better experience for the user, not only visually but through our crisp and delightful audio. We want to hear from our users because it
  is very important to cater to you, the consumer. You can come here to explore and follow us on each project.
  Welcome to Bareware Games, the next frontier of gaming.


#skills:
#- {name: Communication, value: '9'}
#- {name: Organization, value: '7'}
#- {name: Learning, value: '10'}
#- {name: Teaching, value: '6'}
#- {name: Planning, value: '7'}
#- {name: Visual Design, value: '5'}
#- {name: UX Design, value: '8'}
#- {name: Programming, value: '6'}

#-------------------------------
# Projects Section

projects:
- {name: Alone, folder: 'proj-1', file: 'Projects/proj-1.html'}




#-------------------------------
# Staff Section

staff:
- {avatar: 'face-MitchelEppich.jpg',
  name: 'Mitchel Eppich',
  title: 'Owner and Founder, Bareware Games',
  quote: '<p><strong>While pushing the limits of how</strong> games are played — I created Bareware Games to deliver exceptional indie games to the public — we create for our users and will go to any length to please.</p>'}
- {avatar: 'face-Unknown.jpg',
  name: 'You',
  title: 'Staff, Bareware Games',
  quote: '<p><strong>Bareware Games is a team of one</strong> — Could you be the next staff member of Bareware Games and help carve our future.</p>'}
  
#-------------------------------
# Contact Section
  
social:
- {icon: 'twitter', link: 'http://twitter.com/barewaregames'}
- {icon: 'soundcloud', link: 'https://soundcloud.com/bareware-games'}
- {icon: 'github', link: 'https://github.com/BareWareGames'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCl5di63K0Edyg7RcAy-4BSg/feed?filter=2'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/pub/mitchel-eppich/72/a43/a19'}

  
# social netprojects icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
  
  
#-------------------------------
# Donate Section

donate:
- {icon: 'Donate', link: 'http://twitter.com/barewaregames'}

pitch: >
  **I am able to do projects better when I am alive.**
  Any donation will be appreciated and would go to the development of each of the projects Bareware Games undertakes.

  
  
  
